version: '3'
services:
  docker-app:
    image: coders/api-spring-docker
    ports:
      - "8080:8080"
    depends_on:
      - docker-postgres
  docker-postgres:
    image: postgres:10.4
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password